<a href="https://colab.research.google.com/github/ayushpaliwal1920/NLP/blob/main/TextClassification_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

cp: cannot stat 'kaggle.json': No such file or directory

In [2]:
!kaggle datasets download -d lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

Dataset URL: https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews
License(s): other
Downloading imdb-dataset-of-50k-movie-reviews.zip to /content
100% 25.7M/25.7M [00:00<00:00, 116MB/s]

In [3]:
import zipfile
zip_ref = zipfile.ZipFile('/content/imdb-dataset-of-50k-movie-reviews.zip')
zip_ref.extractall('/content')
zip_ref.close()

In [4]:
import pandas as pd
import numpy as np

In [5]:
temp_df = pd.read_csv("/content/IMDB Dataset.csv")

In [6]:
df = temp_df.sample(10000)

In [7]:
df.head()

                                                  review sentiment
4015   Jack Higgins' straightforward thriller about a...  negative
10194  This movie was craptacular. I was so emotional...  negative
34217  A photographer in the small city of Gunsan in ...  positive
26488  What can one say about Elvira that hasn't alre...  positive
28754  Blood Legacy starts with the arrival of lawyer...  negative

In [8]:
df['sentiment'].value_counts()

sentiment
negative    5069
positive    4931
Name: count, dtype: int64

In [9]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(16)

In [11]:
df.drop_duplicates(inplace = True)

In [12]:
df.shape

(9984, 2)

In [13]:
#  Html tags :

import re

def remove_tags(raw_text):
  cleaned_text = re.sub(re.compile('<.*?>'),'',raw_text)
  return cleaned_text

In [14]:
df['review'] = df['review'].apply(remove_tags)

In [15]:
# lowercase

df['review'] = df['review'].apply(lambda x : x.lower())

In [16]:
# stopwords :

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

sw_list = stopwords.words('english')

df['review'] = df['review'].apply(lambda x : [item for item in x.split() if item not in sw_list]).apply(lambda x : " ".join(x))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [17]:
df

                                                  review sentiment
4015   jack higgins' straightforward thriller guilt-r...  negative
10194  movie craptacular. emotionally uninvolved ever...  negative
34217  photographer small city gunsan south korea lea...  positive
26488  one say elvira already said world's press? cla...  positive
28754  blood legacy starts arrival lawyer tom drake (...  negative
...                                                  ...       ...
12619  kudos baxley's dp making look like real movie,...  negative
3069   another eastwood's many movies mixing intrigue...  positive
30687  watched death machines part bci eclipse' drive...  negative
48920  du rififi chez les hommes brilliant film studi...  positive
10535  dragon (jackie chan)is back, rid seas dreaded ...  positive

[9984 rows x 2 columns]

In [18]:
x = df.iloc[:,0:1]
y = df['sentiment']

In [19]:
x

                                                  review
4015   jack higgins' straightforward thriller guilt-r...
10194  movie craptacular. emotionally uninvolved ever...
34217  photographer small city gunsan south korea lea...
26488  one say elvira already said world's press? cla...
28754  blood legacy starts arrival lawyer tom drake (...
...                                                  ...
12619  kudos baxley's dp making look like real movie,...
3069   another eastwood's many movies mixing intrigue...
30687  watched death machines part bci eclipse' drive...
48920  du rififi chez les hommes brilliant film studi...
10535  dragon (jackie chan)is back, rid seas dreaded ...

[9984 rows x 1 columns]

In [20]:
# Encoding :

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(y)

In [21]:
y

array([0, 0, 1, ..., 0, 1, 1])

In [22]:
# train test split

from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2 , random_state = 41)

In [23]:
x_train.shape

(7987, 1)

In [24]:
# APPLYING BOW :

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

In [25]:
x_train_bow = cv.fit_transform(x_train['review']).toarray()
x_test_bow  = cv.transform(x_test['review']).toarray()

In [26]:
# APPLYING Ngram :

from sklearn.feature_extraction.text import CountVectorizer

cv2 = CountVectorizer(ngram_range=(1,2))

x_train_ngram = cv2.fit_transform(x_train['review']).toarray()
x_test_ngram  = cv2.transform(x_test['review']).toarray()

In [27]:
# APPLYING TfIdf :

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

x_train_tfidf = tfidf.fit_transform(x_train['review']).toarray()
x_test_tfidf  = tfidf.transform(x_test['review']).toarray()

In [ ]:
# Model Training : Naive Bayes

from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()
gnb.fit(x_train_bow,y_train)

In [ ]:
y_pred = gnb.predict(x_test_bow)

In [ ]:
from sklearn.metrics import accuracy_score , confusion_matrix

accuracy_score(y_test,y_pred)

In [ ]:
# Model training : Random Forest : Bow
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()

In [ ]:
rfc.fit(x_train_bow,y_train)
y_pred = rfc.predict(x_test_bow)
accuracy_score(y_test,y_pred)

In [ ]:
# # Model training : Random Forest : Ngram

# rfc2 = RandomForestClassifier()

# rfc2.fit(x_train_ngram,y_train)
# y_pred = rfc2.predict(x_test_ngram)

# print(classification_report(y_test,y_pred))
# accuracy_score(y_test,y_pred)

In [ ]:
# # Model training : Random Forest : TFIDF

# rfc2 = RandomForestClassifier()

# rfc2.fit(x_train_tfidf,y_train)
# y_pred = rfc2.predict(x_test_tfidf)

# print(classification_report(y_test,y_pred))
# accuracy_score(y_test,y_pred)