<a href="https://colab.research.google.com/github/ayushpaliwal1920/NLP/blob/main/TextPreprocessing(NLP).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
lakshmi25npathi_imdb_dataset_of_50k_movie_reviews_path = kagglehub.dataset_download('lakshmi25npathi/imdb-dataset-of-50k-movie-reviews')

print('Data source import complete.')

Using Colab cache for faster access to the 'imdb-dataset-of-50k-movie-reviews' dataset.
Data source import complete.

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv

In [4]:
df = pd.read_csv('/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv')
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
dataset = df.sample(n=200, random_state=42).copy()

In [6]:
dataset.head()

                                                  review sentiment
33553  I really liked this Summerslam due to the look...  positive
9427   Not many television shows appeal to quite as m...  positive
199    The film quickly gets to a major chase scene w...  negative
12447  Jane Austen would definitely approve of this o...  positive
39489  Expectations were somewhat high for me when I ...  negative

In [7]:
dataset.shape

(200, 2)

In [8]:
# Lowercasing :

dataset['review'] = dataset['review'].str.lower()
dataset.head()

                                                  review sentiment
33553  i really liked this summerslam due to the look...  positive
9427   not many television shows appeal to quite as m...  positive
199    the film quickly gets to a major chase scene w...  negative
12447  jane austen would definitely approve of this o...  positive
39489  expectations were somewhat high for me when i ...  negative

When regx is used and when BeautifulScoup ?

“I use regex when the HTML is simple, predictable, and performance is critical—like removing basic tags in large datasets using vectorized Pandas operations. However, for complex or nested HTML structures, BeautifulSoup is more reliable because regex cannot correctly parse hierarchical data.”

In [9]:
# Remove 'html' tags : using BeautifulScoup

from  bs4 import BeautifulSoup

dataset['review'] = dataset['review'].apply(lambda x : BeautifulSoup(x , 'html.parser').get_text())

dataset.head()

                                                  review sentiment
33553  i really liked this summerslam due to the look...  positive
9427   not many television shows appeal to quite as m...  positive
199    the film quickly gets to a major chase scene w...  negative
12447  jane austen would definitely approve of this o...  positive
39489  expectations were somewhat high for me when i ...  negative

In [10]:
# Remove 'html' tags : using Regx(regular expression)

import re

def remove_html(text):
    if not isinstance(text, str):
        return text
    pattern = re.compile(r'<[^>]+>')
    return pattern.sub('', text)

dataset['review'] = dataset['review'].apply(remove_html)

In [11]:
# Remove 'URLs' : “I use the pattern https?://\S+|www\.\S+ to capture both HTTP/HTTPS and www-based URLs, removing everything until the next whitespace.”

def remove_url(text):
    if not isinstance(text, str):
        return text
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub('', text)

dataset['review'] = dataset['review'].apply(remove_url)

In [12]:
# Remove 'Punctuation' :

import string

def remove_punc(text):
    if not isinstance(text , str):
        return text
    text = text.translate(str.maketrans('', '', string.punctuation))
    return text

dataset['review'] = dataset['review'].apply(remove_punc)

In [13]:
dataset.head()

                                                  review sentiment
33553  i really liked this summerslam due to the look...  positive
9427   not many television shows appeal to quite as m...  positive
199    the film quickly gets to a major chase scene w...  negative
12447  jane austen would definitely approve of this o...  positive
39489  expectations were somewhat high for me when i ...  negative

In [14]:
# Chat word treatment : when we have this type of data :
chat_words = {
    "A3": "Anytime, Anywhere, Anyplace",
    "ADIH": "Another Day In Hell",
    "AFK": "Away From Keyboard",
    "AFAIK": "As Far As I Know",
    "ASAP": "As Soon As Possible",
    "ASL": "Age, Sex, Location",
    "ATK": "At The Keyboard",
    "ATM": "At The Moment",
    "BAE": "Before Anyone Else",
    "BAK": "Back At Keyboard",
    "BBL": "Be Back Later",
    "BBS": "Be Back Soon",
    "BFN": "Bye For Now",
    "B4N": "Bye For Now",
    "BRB": "Be Right Back",
    "BRUH": "Bro",
    "BRT": "Be Right There",
    "BSAAW": "Big Smile And A Wink",
    "BTW": "By The Way",
    "BWL": "Bursting With Laughter",
    "CSL": "Can’t Stop Laughing",
    "CU": "See You",
    "CUL8R": "See You Later",
    "CYA": "See You",
    "DM": "Direct Message",
    "FAQ": "Frequently Asked Questions",
    "FC": "Fingers Crossed",
    "FIMH": "Forever In My Heart",
    "FOMO": "Fear Of Missing Out",
    "FR": "For Real",
    "FWIW": "For What It's Worth",
    "FYP": "For You Page",
    "FYI": "For Your Information",
    "G9": "Genius",
    "GAL": "Get A Life",
    "GG": "Good Game",
    "GMTA": "Great Minds Think Alike",
    "GN": "Good Night",
    "GOAT": "Greatest Of All Time",
    "GR8": "Great!",
    "HBD": "Happy Birthday",
    "IC": "I See",
    "ICQ": "I Seek You",
    "IDC": "I Don’t Care",
    "IDK": "I Don't Know",
    "IFYP": "I Feel Your Pain",
    "ILU": "I Love You",
    "ILY": "I Love You",
    "IMHO": "In My Honest/Humble Opinion",
    "IMU": "I Miss You",
    "IMO": "In My Opinion",
    "IOW": "In Other Words",
    "IRL": "In Real Life",
    "IYKYK": "If You Know, You Know",
    "JK": "Just Kidding",
    "KISS": "Keep It Simple, Stupid",
    "L": "Loss",
    "L8R": "Later",
    "LDR": "Long Distance Relationship",
    "LMK": "Let Me Know",
    "LMAO": "Laughing My A** Off",
    "LOL": "Laughing Out Loud",
    "LTNS": "Long Time No See",
    "M8": "Mate",
    "MFW": "My Face When",
    "MID": "Mediocre",
    "MRW": "My Reaction When",
    "MTE": "My Thoughts Exactly",
    "NVM": "Never Mind",
    "NRN": "No Reply Necessary",
    "NPC": "Non-Player Character",
    "OIC": "Oh I See",
    "OP": "Overpowered",
    "PITA": "Pain In The A**",
    "POV": "Point Of View",
    "PRT": "Party",
    "PRW": "Parents Are Watching",
    "ROFL": "Rolling On The Floor Laughing",
    "ROFLOL": "Rolling On The Floor Laughing Out Loud",
    "ROTFLMAO": "Rolling On The Floor Laughing My A** Off",
    "RN": "Right Now",
    "SK8": "Skate",
    "STATS": "Your Sex And Age",
    "SUS": "Suspicious",
    "TBH": "To Be Honest",
    "TFW": "That Feeling When",
    "THX": "Thank You",
    "TIME": "Tears In My Eyes",
    "TLDR": "Too Long, Didn’t Read",
    "TNTL": "Trying Not To Laugh",
    "TTFN": "Ta-Ta For Now!",
    "TTYL": "Talk To You Later",
    "U": "You",
    "U2": "You Too",
    "U4E": "Yours For Ever",
    "W": "Win",
    "W8": "Wait...",
    "WB": "Welcome Back",
    "WTF": "What The F**k",
    "WTG": "Way To Go!",
    "WUF": "Where Are You From?",
    "WYD": "What You Doing?",
    "WYWH": "Wish You Were Here",
    "ZZZ": "Sleeping, Bored, Tired"
}

In [15]:
# Chat word treatment : ex : replace Gn with Good night

def chat_conversion(text) :
    new_text = []
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

dataset['review'] = dataset['review'].apply(chat_conversion)

In [16]:
chat_conversion('IMHO is the best')

'In My Honest/Humble Opinion is the best'

In [ ]:
# Spelling Correction :

from textblob import TextBlob

def correct_text(text):
    if not isinstance(text, str):
        return text
    return str(TextBlob(text).correct())

dataset['review'] = dataset['review'].apply(correct_text)

In [ ]:
# example

incorrect = 'ceertain condition during sevrl gneration are modifred in ths same mannerr.'
textblb = TextBlob(incorrect)

textBlb.correct().string

In [22]:
# Removing Stop words :  ex : the , are , my , a etc

import nltk

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    if not isinstance(text, str):
        return text

    words = text.split()  # simple tokenization
    filtered = [word for word in words if word.lower() not in stop_words]

    return " ".join(filtered)

dataset['review'] = dataset['review'].apply(remove_stopwords)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [23]:
dataset.head()

                                                  review sentiment
33553  really liked summerslam due look arena curtain...  positive
9427   many television shows appeal quite many differ...  positive
199    film quickly gets major chase scene ever incre...  negative
12447  jane austen would definitely approve onegwynet...  positive
39489  expectations somewhat high went see movie thou...  negative

In [24]:
# Handling 'Emoji' :

# Remove Emoji :

import re
def remove_emoji(text):
    if not isinstance(text, str):
        return text

    emoji_pattern = re.compile(
        "["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags
        u"\U00002700-\U000027BF"  # dingbats
        u"\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE
    )

    return emoji_pattern.sub('', text)

In [28]:
!pip install emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 14.5 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0

In [29]:
#  Replace emoji :

import emoji
import re

def replace_emoji(text):
    if not isinstance(text, str):
        return text

    # Convert emoji to text
    text = emoji.demojize(text, delimiters=(" ", " "))

    # Replace underscores with space
    text = text.replace("_", " ")

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [30]:
dataset['review'] = dataset['review'].apply(replace_emoji)

In [31]:
# Tokenization1 : word tokenization

sent1 = 'i am going to new delhi'
sent1.split()

['i', 'am', 'going', 'to', 'new', 'delhi']

In [32]:
# Tokenization2 : sentence tokenization

sent2 = "I am going to delhi.I will stay there for 3 days .Lets\'s hope the trip to be great."
sent2.split(".")

['I am going to delhi',
 'I will stay there for 3 days ',
 "Lets's hope the trip to be great",
 '']

In [33]:
# Problem with split fxn :

sent3 = "I am going to delhi!"
sent3.split()

['I', 'am', 'going', 'to', 'delhi!']

In [34]:
# Tokenization : using spacy lib (best and imp)


import spacy
nlp = spacy.load("en_core_web_sm")

def tokenize_spacy(text):
    if not isinstance(text, str):
        return text

    doc = nlp(text)
    return [token.text for token in doc]

In [37]:
# Tokenization : split text into words : IMportant (Recommended) using nltk lib

from nltk.tokenize import word_tokenize , sent_tokenize
nltk.download('punkt')
nltk.download('punkt_tab') #  important here

def tokenize(text):
    if not isinstance(text, str):
        return text
    return word_tokenize(text)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [38]:
dataset['review'] = dataset['review'].apply(tokenize)

In [39]:
dataset.head()

                                                  review sentiment
33553  [really, liked, summerslam, due, look, arena, ...  positive
9427   [many, television, shows, appeal, quite, many,...  positive
199    [film, quickly, gets, major, chase, scene, eve...  negative
12447  [jane, austen, would, definitely, approve, one...  positive
39489  [expectations, somewhat, high, went, see, movi...  negative

In [40]:
# Stemming : reducing word to their root/base form. uses in information retrieval systems such as search engines .

# using nltk PortStemmer

from nltk.stem import PorterStemmer

ps = PorterStemmer()

def stemming_nltk(text):
    if not isinstance(text, str):
        return text

    words = text.split()
    stemmed_words = [ps.stem(word) for word in words]

    return " ".join(stemmed_words)

In [41]:
# using stemming  with tokenizer :

from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

ps = PorterStemmer()

def stemming2(text):
    if not isinstance(text, str):
        return text

    words = word_tokenize(text)
    return " ".join([ps.stem(w) for w in words])

In [42]:
# dataset['review'] = dataset['review'].apply(stemming_nltk)

In [43]:
# Lemitization : reduces word to thier root insuring that the root word belong to the language

# using nltk :

from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    if not isinstance(text , str):
        return text
    words = word_tokenize(text)

    return " ".join([lemmatizer.lemmatize(w) for w in words])

In [44]:
# using spacy : Imp / Best

import spacy

nlp = spacy.load('en_core_web_sm')

def lemmatize_text2(text):
    if not isinstance(text, str):
        return text

    doc = nlp(text)
    return " ".join([token.lemma_ for token in dox])

lemmetization our review using spacy :

In [45]:
dataset['review'] = dataset['review'].apply(
    lambda words: [token.lemma_ for token in nlp(" ".join(words))]
)

In [46]:
dataset.head()

                                                  review sentiment
33553  [really, like, summerslam, due, look, arena, c...  positive
9427   [many, television, show, appeal, quite, many, ...  positive
199    [film, quickly, get, major, chase, scene, ever...  negative
12447  [jane, austen, would, definitely, approve, one...  positive
39489  [expectation, somewhat, high, go, see, movie, ...  negative